### ISSUE TITLE
Full website not on github

### ISSUE THREAD

**Issue by JackCDK** [NLDev/nulldev#6]
code for http://nulldev.org/mobile/ is no on github, There are some problems with it.

**Comment by NLDev** [comment]
That's because I used a template for it

**Comment by JackCDK** [comment]
why be cheap when making a .org website

**Comment by NLDev** [comment]
because nulldev.com was already taken :)

**Comment by JackCDK** [comment]
no, it's for sale
![screenshot - 220117 - 00 29 23](https://cloud.githubusercontent.com/assets/20729349/22178809/e130d25a-e039-11e6-9679-80217b7564a7.png)

**Comment by NLDev** [comment]
Not gonna make an offer fro $200+ 
Can we close this now?

**Comment by JackCDK** [comment]
it is closed 
![screenshot - 22011a7 - 00 42 13](https://cloud.githubusercontent.com/assets/20729349/22178895/b45a1690-e03b-11e6-8675-77148839ab57.png)
what u talking about?

**Comment by NLDev** [comment]
rly -.-

**Comment by JackCDK** [comment]
what was that for it was already close lol

**Comment by NLDev** [comment]
I know. That was just to let you know that we should stop chatting here now

**Comment by JackCDK** [comment]
why

**Comment by NLDev** [comment]
why not

**Comment by JackCDK** [comment]
just do this lol
![screenshot - 220117 - 00 50 14](https://cloud.githubusercontent.com/assets/20729349/22178954/d44b095e-e03c-11e6-9c9e-3f22955110a3.png)
dont you know how github works?
